FROM continuumio/miniconda3

# Create the environment:
WORKDIR /env
COPY env.yml .
RUN conda env create -f env.yml

RUN mkdir /config
RUN mkdir /datafiles

# Make RUN commands use the new environment:
RUN echo "conda activate coacervate_env" >> ~/.bashrc

ENTRYPOINT ["conda", "run", "-n", "coacervate_env"]
CMD ["snakemake", "-c=1", "-s=/config/Snakefile"]