FROM continuumio/miniconda3

WORKDIR /app

# Create the environment:
COPY env.yml .
RUN conda env create -f env.yml

# Make RUN commands use the new environment:
RUN echo "conda activate coacervate_env" >> ~/.bashrc
SHELL ["/bin/bash", "--login", "-c"]