configfile: "/data/config/config.yml"

# Override default config
config['regs'] = ['chr21']

include: "rules/calling.smk"

rule all:
    input: 
        "/data/results/combi_out/chr21_database/"
    output:
        touch("/data/results/test.done")
