apiVersion: v1

kind: PersistentVolumeClaim

metadata:
  name: yagna-pvc
  labels:
    {{- include "coacervate.labels" . | nindent 4 }}

spec:
  storageClassName: manual

  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
