apiVersion: v1

kind: PersistentVolume

metadata:
  name: {{ .Values.yagnaPvName }}
  labels:
    {{- include "coacervate.labels" . | nindent 4 }}
    module: yagna

spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: {{ .Values.storage.yagnaHostPath }}
