apiVersion: v1

kind: PersistentVolumeClaim

metadata:
  name: {{ .Values.yagnaPvcName }}
  labels:
    {{- include "coacervate.labels" . | nindent 4 }}
    module: yagna

spec:
  storageClassName: manual

  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  volumeName: {{ .Values.yagnaPvName }}
