apiVersion: v1
kind: Service
metadata:
  name: {{ include "coacervate.fullname" . }}-yagna-service
  labels:
    service: yagna
spec:
  ports:
  - port: 7465
    protocol: TCP
  selector:
    {{- include "coacervate.selectorLabels" . | nindent 4 }}