apiVersion: v1

kind: PersistentVolume

metadata:
  name: {{ include "coacervate.fullname" . }}-yagna-pv
  labels:
    {{- include "coacervate.labels" . | nindent 4 }}

spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: {{ .Values.storage.yagnaHostPath }}
