apiVersion: apps/v1

kind: Deployment

metadata:
  name: coacervate-deployment

  labels:
    app: coacervate

spec:
  replicas: 1

  selector:
    matchLabels:
      app: coacervate

  template:
    metadata:
      labels:
        app: coacervate

    spec:
      volumes:
        - name: coacervate-pv-storage
          persistentVolumeClaim:
            claimName: coacervate-pvc
        - name: yagna-socket
          emptyDir: {}
      containers:
        - name: yagna
          image: yagna:latest
          imagePullPolicy: Never
          # command: ["sleep", "3600"]
          volumeMounts:
            - name: coacervate-pv-storage
              mountPath: /root/.local/share/
            - name: yagna-socket
              mountPath: /tmp
        - name: requestor
          image: coacervate:latest
          imagePullPolicy: Never
          command: ["python", "/data/workflow/scripts/hello.py"]
          # command: ["sleep", "3600"]
          volumeMounts:
            - name: yagna-socket
              mountPath: /tmp
        # - name: aio
        #   image: coacervate_aio:latest
        #   imagePullPolicy: Never
        #   # command: ["python", "/data/workflow/scripts/hello.py"]
        #   command: ["sleep", "3600"]
        #   volumeMounts:
        #     - name: yagna-socket
        #       mountPath: /tmp
        #   securityContext:
        #     runAsUser: 0
        #   env:
        #     - name: YAGNA_APPKEY
        #       value: bc90ecb7538440e5ad541b3ca8962884
        # - name: yagna-check
        #   image: yagna:latest
        #   imagePullPolicy: Never
        #   command: ["sleep", "3600"]
        #   volumeMounts:
        #     - name: yagna-socket
        #       mountPath: /tmp
