apiVersion: v1

kind: PersistentVolume

metadata:
  name: coacervate-pv

spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: "/data/requestor_pv/"