apiVersion: batch/v1

kind: Job

metadata:
  name: snakemake-job

  labels:
    app: coacervate

spec:

  template:
    metadata:
      labels:
        task: snakemake

    spec:
      volumes:
        - name: coacervate-pv-storage
          persistentVolumeClaim:
            claimName: coacervate-pvc
      containers:
        - name: requestor
          image: coacervate:latest
          imagePullPolicy: Never
          command: ["snakemake", "-f", "/data/workflow/Snakefile", "-c", "4"]
          volumeMounts:
            - name: coacervate-pv-storage
              mountPath: /tmp
              subPath: socket
          env:
          - name: YAGNA_API_URL
            value: "http://yagna-service:7465"
      restartPolicy: Never
