configfile: "/data/config/config.yml"

# Override default config
config['regs'] = ['chr21', 'chr22']

include: "rules/calling.smk"

rule all:
    input: 
        "/data/results/gather_out/project_output.vcf.gz"
    output:
        touch("/data/results/test.done")
