test:
  pvcLabel: test-storage-label
  pvcName: test-pvc
  assetVolName: test-assets-volume
  assetPath: ""

  defaultCheckCom: '["python3", "/checker/cli.py"]'
  registered:
    - name: index-cram
      subPath: index_cram
    - name: split-cram
      subPath: split_cram
    - name: index-split-cram
      subPath: index_split_cram
    - name: gather-vcfs
      subPath: gather_vcfs

