apiVersion: apps/v1

kind: Deployment

metadata:

  name: coacervate-deployment

  labels:

    app: coacervate

spec:

  replicas: 1

  selector:

    matchLabels:

      app: coacervate

  template:

    metadata:

      labels:

        app: coacervate

    spec:

      containers:

      - name: yagna

        image: yagna:latest

        imagePullPolicy: Never

        ports:

        - containerPort: 80
