configfile: "/data/config/config.yml"

# Override default config
config['regs'] = ['chr21']
config['samples'] = ['HG03633']

include: "rules/calling.smk"

rule all:
    input: 
        "/data/results/hc_out/chr21/HG03633_chr21.g.vcf.gz"
    output:
        touch("/data/results/test.done")
